* ADA 2.0B Project
[jeraman.info](http://jeraman.info), 2010
contact - jbcj [at] cin.ufpe.br


* About
Ada v2.0b is a computer programmer created in 2010.

It was designed for creating programs using Pure Data (a graphical programming language), in a Live Coding session, based on its own (sub/o)jectivity.

This is done through the analysis of what happens in the Kernel (the central component of most computer Operating Systems) of the machine, in real-time. Based on this, Ada 2.0b creates an audiovisual Live Coding performance, without human intervention.

Inspired by the Emotional Kernel Panic and the Marvim Gainsbug projects, this project was developed in Pure Data and Python (using a special module for Pd dynamic patching, called Pyata) by Jeraman.

For further informations, visit (sorry, in portuguese):

[http://jeraman.info/​ada-2-0b/]​(http://jeraman.info/​ada-2-0b/)


* Requirements 
- Ubuntu Jaunty 9.04;
- Pure Data 0.41-4;
- Python 2.6.2;


* How to Run
1. Open terminal;
2. Type the following command and wait a few seconds:

	$ sudo python main.py

3. Maximize the Pure Data window called "new";
4. Wait the counter to finish;
5. Voilá! Wait the performance to finish for checking if everything went fine;

